### ISSUE TITLE
Deviations from BIDS

### ISSUE THREAD

**Issue by jdkent** [TKoscik/nimg_core#3]
@TKoscik 
I was curious what were the motivations to deviate from the BIDS standard?
Some of this could be valuable discussion for [BIDS 2.0](https://docs.google.com/document/d/1LEgsMiisGDe1Gv-hBp1EcLmoz7AlKj6VYULUgDD3Zdw/edit#heading=h.bg12xpyahj6a)

Specifically, the deviations are:
1. there would be a `sourcedata` directory under the `${projectName}` folder
2. the `dicom` directory would be in the `sourcedata` directory
2. there wouldn't be a `nifti` directory and the subjects would be under the `${projectName}` folder
3. the `qa` directory would be in the `derivatives` directory
4. the `orig` would be in the `sourcedata` directory
5. the top level of the `derivatives` folder would be organized by pipeline instead of by subject
6. the `fsurf` directory would be in `derivatives`
7. the `lut` directory would be somewhere else (perhaps in an `atlas` directory under `derivatives`?
8. the `stimuli` directory would be under the `sourcedata` directory
9. some information in `summary` would go into `dataset_description.json` and into the `derivatives` directory.

These deviations will currently make it more difficult to share the nifti data on [openneuro](https://openneuro.org/) without a script to address some of the above changes to make a valid BIDS dataset (if eventual sharing is the goal). 

Then to share derivatives, there would be additional scripts necessary to conform the subject oriented output into a pipeline oriented output.

I say this with the intention of promoting less work in the future in case people want to share their data or run their own analyses without running into problems because the structure is not bids-validated, (e.g. see [BIDS-APPS](https://github.com/BIDS-Apps)). Without modification, none of the bids-apps would work with this organization.

So I wanted to hear your thoughts about the deviations (there are probably benefits that I'm not seeing, but would like to know about since it could help improve the BIDS standard).

**Comment by TKoscik** [comment]
some quick responses:
the deviations in folder structure are intended to meet two main criteria: 1) transparency in terms of folder contents (e.g., dicoms and only dicoms in the dicom folder) and 2) usability, to be more readily useful for researchers who are our clients, e.g., they can find everything they need in the summary folder and not really have to look elsewhere). our tertiary concerns are dealing with legacy-type data and expanding beyond neuroimaging since this is really a small component to health-related research more broadly. The ability to use BIDS-APPS is not on our radar at this point.

one thing you did not mention was our deviations from file naming conventions... there is a lot of rich data that helps interpret brain images that we can easily add to the file names (like b-values and phase encoding directions for dwi) and having a site variable that encodes location and scanner to a specific location and piece of hardware are critical for multisite studies.

1-2. we felt dicom is a more appropriate name, i.e. labelling data as transparent to what it is, and doesn't require an additional directory level to do so.
3. nifti folder to be the home for converted dicoms, again being transparent as to the contents but also to leave room for non-nifti datatypes like minc.
4. qa does not belong in the derivatives, these are quality assurance and calibration scans (beyond localizers and things like that) things like water solubility scans on phantoms, they are raw not derived. we may move those into the cal folder.
5. orig is not sourcedata, these are nifti files extracted from dicoms that come off the scanner and precede any on-scanner processing. as with 1-3 i think it is more useful to use to be transparent regarding data format and stage of processing.
6-7 these are in error, i haven't gotten around to fixing the bad commits
8-9. again this organization is meant to be transparent regarding their content and need to be expandable in a more efficient way to deal with huge amounts of data beyond what is typically stored in BIDS.
10. summaries cannot go into tsv files, the amount of data would make those less useful, and we need mechanisms to protect any identifiable information from being accidentally shared.

**Comment by jdkent** [comment]
Thanks for the responses!

I didn't look closely at the filenames, but I do see one bids compatible solution (place the site and scanner variables in the `participants.tsv`)
and phase-encoding direction could use the key `acq`, but this information should also be included in the sidecar `json` file.

1-2. as for dicom, you could place the dicom in the `sourcedata` folder
3. nifti, for better or for worse has been adopted as the defacto standard imaging format for BIDS. This is my ignorance, but which groups at UofI use other imaging formats besides nifti (such as minc?)
4. Ah, I see, these are quality assurance scans, and not data about the scans, then I'm on board with that.
5. thanks for the clarification, then my opinion would be to use the `acq` key to say they are orig (e.g. `acq-orig`, but since these scans are unlikely to be used in further processing, I don't have a strong preference for that.
6-7. got it.
8-9. more on this below
10. did you mean `json` files? To further comment, I think we would need to be clear on the types of information that goes into each summary file.

I totally agree with your two main criteria transparency and usability w.r.t directory structure is important; I cannot comment on trying to adapt legacy data, but I do know BIDS supports other modalities/information besides neuroimaging data (depending on what specifically you are trying to adopt). I am curious what large pieces of data you are referring to that BIDS does not currently accommodate (read 8-9). 

I would take into account two additional criteria as principles:
1. leveraging existing work
BIDS is now more than a draft specifying how one should name files and directories. There are now utilities surrounding it that make that type of data easier to work with, either through prepackaged apps (e.g. mriqc, fmriprep, the rest of bids-apps, [datalad](https://www.datalad.org/)) or through libraries that make developing your own apps easier (e.g. [pybids](https://github.com/bids-standard/pybids). There is also a [bids-starter-kit](https://github.com/bids-standard/bids-starter-kit), making the education process that much simpler on your end. Leveraging these existing utilities should reduce the overall workload of implementing this service. This will be at the cost of some potential clarity, but I believe the tools/existing documentation that are unlocked by adopting BIDS make up for the loss of clarity. 

As another potential pitfall down the line as BIDS becomes more popular*, researchers may become more aware of that structure and then the deviations may confuse researchers as they need to be educated on what those deviations are, working against your main criteria.

2. being inter-operable with a broader community
If utilities do not exist yet that your group would develop, then making them interface with vanilla-bids would be a great boon for the broader community, and could put your group on the map for contributing excellent software, that others would use and help improve, improving your service overall.

In short, I think leveraging the work of many people makes your team and service stronger, and could pay great dividends in terms of being recognized for your work (by helping develop utilities that interface with bids), and increase recognition of the University of Iowa. Importantly, this will move the field of neuroscience further towards sharing of code/data and making collaboration even easier. Taking these additional principles into account, I believe the benefits of fully adopting bids outweigh the costs in transparency and usability.

To be fair, I do not have an equation that takes the cost of transparency and usability and puts it into the same currency as the cost of (partially) re-creating the wheel, and not being able to interface with the broader community, so the above statement is based on my own biases. 

*Is BIDS becoming more popular?
- that standard has expanded to include [MEG-EEG data](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6007085/)
- BIDS-derivatives has [NIH funding](http://grantome.com/grant/NIH/R24-MH114705-02)
- [NIH will use BIDS as the standard for archiving neuroimaging data](https://groups.google.com/forum/#!msg/bids-discussion/NeqFO-lJhsc/_atcTFfIBQAJ) I couldn't substantiate this claim besides this person saying so.
